title: USPdev
description: devs da Universidade de São Paulo

# foram para o .env
#baseurl: "/"
#url: "https://uspdev.github.io/"

# Build settings
markdown: kramdown
# theme: jekyll-theme-cayman
theme: style.css

menu:
  0:
    url: contribua
    text: Contribua!
  1:
    url: treinamentos
    text: Treinamentos
  2:
    url: glossario
    text: Glossário
  3:
    url: projetos
    text: Projetos

    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
