title: USPdev
description: devs da Universidade de São Paulo

# para o site publicado, indique a pasta, pode ser no .env também
baseurl: ""

# por enquanto não está sendo usado
url: "http://143.107.233.112"
#url: "http://uspdev.github.io/"

# Build settings
markdown: kramdown
# theme: jekyll-theme-cayman
theme: style.css

menu:
  0:
    text: Contribua!
    url: contribua
  1:
    text: Treinamentos
    url: treinamentos
  2:
    text: Glossário
    url: glossario
  3:
    text: Projetos
    url: projetos

    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
